apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sample-web-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
      - 20.185.9.115.nip.io # IMPORTANT: update <ingress ip> with the dashed public IP of your ingress, for example frontend.13-68-177-68.nip.io
      secretName: sample-web-cert
  rules:
  - host: 20.185.9.115.nip.io
    http:
      paths:
      - backend:
          serviceName: josecarlosanpedrokubernetesnodejs
          servicePort: 80
        path: /server
      - backend:
          serviceName: josecarlosanpedrokubernetesreactjs
          servicePort: 80
        path: /