apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sample-web-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: 20.185.9.115.nip.io
    http:
      paths:
      - backend:
          serviceName: josecarlosanpedrokubernetesnodejs
          servicePort: 80
        path: /server